#!/bin/bash

if [ $# -ne 1 ]; then
    echo Usage: $0 VERSION
    exit 1
fi

version="$1"

# If version matches ^\d+\.\d+\.\d+$, we consider it to be a release
# version.

echo $version | grep -q -P '^\d+\.\d+\.\d+$'

