name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ag_version: ["7.3.1", "7.3.0", "7.2.0", "7.1.0", "7.0.4"]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./agdock build --version=${{ matrix.ag_version }} --tag=franzinc/agraph:v${{ matrix.ag_version }}
      - name: Push
        run: ./agdock push --image=franzinc/agraph:v${{ matrix.ag_version }}
